name: Dev Pipeline

on:
  pull_request:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build:
    name: Test and Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM Packages
        run: yarn install --frozen-lockfile
        
      - name: Run Tests
        run: yarn test
        
      - name: Build Project
        run: yarn build