name: Prod Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Test and Build Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v2

      - name: Install Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM Packages
        run: yarn install --frozen-lockfile
        
      - name: Run Tests
        run: yarn test
        
      - name: Build Project
        run: yarn build
        
      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: build-artifact
          path: ./build

  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Build Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-artifact
          path: ./build
          
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.4.1
        with:
          build_dir: ./build
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Bump and Push SemVer Tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          
      - name: Create Release Using SemVer Tag
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          release_name: Release ${{ steps.tag_version.outputs.new_tag }}
          body: ${{ steps.tag_version.outputs.changelog }}